site_name: PSI* du Lycée La Martinière Monplaisir
site_url: https://psilamartin.github.io/
#repo_url: https://github.com/xpessoles/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking # Menu de la page à droite ?
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips  # pour les infobulles sur les mots ?
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Mode sombre
      primary: deep orange
      accent: deep orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Mode clair
      primary: deep orange
      accent: deep orange
  icon:
    logo: fontawesome/solid/wave-square 
    
    
plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psilamartin

  
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets   # pour les infobulles sur les mots ?
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list           # pour les infobulles sur les mots ?
  - abbr                # pour les infobulles sur les mots ?
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  
copyright: |
  &copy; 2024 <a href="https://github.com/psilamartin"  target="_blank" rel="noopener">Team PSI*</a>


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/feedback.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Acceuil: index.md
  - Organisation : orga.md
  - Maths: maths.md
  - Physique: physique.md
  - SII: sii.md
  - Informatique : info.md
  